server {
    listen 80;
    listen [::]:80;

    server_name sistema._domain_;

    root /sites/sys/browser;
    index index.html;

    # No mostrar la versión de Nginx
    server_tokens off;

    # ------------------------------------------------------------
    # Cabeceras de seguridad
    # ------------------------------------------------------------

    # Evita que el sitio sea cargado dentro de frames o iframes
    add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self'; script-src-attr 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; media-src 'self' blob:;" always;

    # Clickjacking para navegadores antiguos
    add_header X-Frame-Options "DENY" always;

    # Evita que el navegador adivine tipos MIME
    add_header X-Content-Type-Options "nosniff" always;

    # Reduce la información enviada en la cabecera Referer
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Permite cámara únicamente en Frontend
    add_header Permissions-Policy "camera=(self), microphone=(), geolocation=()" always;

    # Dominio y subdominios con HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # ------------------------------------------------------------
    # Angular
    # ------------------------------------------------------------

    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ------------------------------------------------------------
    # Proxy inverso hacia la API
    # ------------------------------------------------------------

    location /api/ {
        proxy_http_version 1.1;

        proxy_pass _apiprotocol_://_apiuri_;

        # Conservar el dominio público solicitado por el cliente
        proxy_set_header Host $host;

        # El acceso público siempre es HTTPS mediante Cloudflare
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;

        proxy_set_header X-Forwarded-For "";

        # Evita exponer cabeceras comunes de frameworks backend
        proxy_hide_header X-Powered-By;
    }
}
