services:
  api:
    build: ./api
    container_name: api
    ports:
      - 8080:8080
    networks:
      - network
    env_file:
      - .env
    environment:
      - DEFAULT_CONNECTION=${SERVER}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ENCRYPT_KEY=${EKEY}
    volumes:
      - ./api:/app
    profiles:
      - api

  sys:
    build: ./sys
    container_name: sys
    ports:
      - 8082:4300
    networks:
      - network
    depends_on:
      - api
    volumes:
      - ./sys:/app

  db:
    build: ./db
    container_name: db
    ports:
      - 8083:3306
    networks:
      - network
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB}
      - MYSQL_ROOT_PASSWORD=${PASSWD}
    profiles:
      - api

networks:
  network:
    driver: bridge
