services:
  db:
    build: ./db
    container_name: db
    networks: [network]
    env_file:
      - .db-env
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./backend
      target: api
    container_name: api
    networks: [network]
    ports:
      - 8080:8080
    env_file:
      - .dotnet-env
    depends_on:
      db:
        condition: service_healthy

networks:
  network:
    driver: bridge
