// <auto-generated />
using System;
using MRCD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRCD.Infrastructure.Migrations;

[DbContext(typeof(Persistence.AppContext))]
[Migration("20260224141919_UniqueEntityName")]
partial class UniqueEntityName
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.22")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("MRCD.Domain.AccountingMovement.AccountingMovement", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<decimal>("Amount")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.HasKey("ID")
                    .HasName("PK_AccountingMovement_ID");

                b.ToTable("accounting_movement", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Attendance.Attendance", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<bool>("IsAttendance")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid>("PersonId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("UserId")
                    .HasColumnType("char(36)");

                b.HasKey("ID")
                    .HasName("PK_Attendance_ID");

                b.HasIndex("PersonId");

                b.HasIndex("UserId");

                b.ToTable("attendance", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Charge.Charge", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<decimal>("Amount")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)");

                b.HasKey("ID")
                    .HasName("PK_Charge_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Charge_Name");

                b.ToTable("charge", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Degree.Degree", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)");

                b.HasKey("ID")
                    .HasName("PK_Degree_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Degree_Name");

                b.ToTable("degree", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Document.Document", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)");

                b.HasKey("ID")
                    .HasName("PK_Document_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Document_Name");

                b.ToTable("document", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Parent.Parent", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<bool>("IsMasculine")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("Phone")
                    .HasColumnType("longtext");

                b.HasKey("ID")
                    .HasName("PK_Parent_ID");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("UX_Parent_NormalizedName");

                b.ToTable("parent", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Parent.ParentPerson", b =>
            {
                b.Property<Guid>("ParentId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("PersonId")
                    .HasColumnType("char(36)");

                b.Property<bool>("IsParent")
                    .HasColumnType("tinyint(1)");

                b.HasKey("ParentId", "PersonId", "IsParent")
                    .HasName("PK_ParentPerson_ParentId_PersonId_IsParent");

                b.HasIndex("PersonId");

                b.ToTable("parent_person", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Person.Person", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Address")
                    .HasColumnType("longtext");

                b.Property<DateOnly>("DOB")
                    .HasColumnType("date");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)");

                b.Property<bool>("IsMasculine")
                    .HasColumnType("tinyint(1)");

                b.Property<bool>("IsSunday")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid>("LastDegreeId")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(65)
                    .HasColumnType("varchar(65)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(65)
                    .HasColumnType("varchar(65)");

                b.Property<string>("Parish")
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)");

                b.Property<string>("Phone")
                    .HasColumnType("longtext");

                b.Property<DateOnly>("RegistrationDate")
                    .HasColumnType("date");

                b.HasKey("ID")
                    .HasName("PK_Person_ID");

                b.HasIndex("LastDegreeId");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("UX_Person_NormalizedName");

                b.ToTable("person", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonCharge", b =>
            {
                b.Property<Guid>("PersonId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("ChargeId")
                    .HasColumnType("char(36)");

                b.HasKey("PersonId", "ChargeId")
                    .HasName("PK_PersonCharge_PersonId_ChargeId");

                b.HasIndex("ChargeId");

                b.ToTable("person_charge", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonDocument", b =>
            {
                b.Property<Guid>("PersonId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("char(36)");

                b.HasKey("PersonId", "DocumentId")
                    .HasName("PK_PersonDocument_PersonId_DocumentId");

                b.HasIndex("DocumentId");

                b.ToTable("person_document", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonSacrament", b =>
            {
                b.Property<Guid>("PersonId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("SacramentId")
                    .HasColumnType("char(36)");

                b.HasKey("PersonId", "SacramentId")
                    .HasName("PK_PersonSacrament_PersonId_SacramentId");

                b.HasIndex("SacramentId");

                b.ToTable("person_sacrament", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Planner.Activity", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.HasKey("ID")
                    .HasName("PK_Activity_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Activity_Name");

                b.ToTable("activity", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Planner.ActivityStage", b =>
            {
                b.Property<Guid>("ActivityId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("StageId")
                    .HasColumnType("char(36)");

                b.Property<Guid?>("UserId")
                    .HasColumnType("char(36)");

                b.Property<bool>("IsUserMain")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Notes")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.HasKey("ActivityId", "StageId", "UserId")
                    .HasName("PK_ActivityStage_ActivityId_StageId_UserId");

                b.HasIndex("StageId");

                b.HasIndex("UserId");

                b.ToTable("activity_stage", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Planner.Stage", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.HasKey("ID")
                    .HasName("PK_Stage_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Stage_Name");

                b.ToTable("stage", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Role.Permission", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)");

                b.HasKey("ID")
                    .HasName("PK_Permission_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Permission_Name");

                b.ToTable("permission", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Role.Role", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("varchar(3)");

                b.HasKey("ID")
                    .HasName("PK_Role_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Role_Name");

                b.ToTable("role", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Role.RolePermission", b =>
            {
                b.Property<Guid>("RoleID")
                    .HasColumnType("char(36)");

                b.Property<Guid>("PermissionID")
                    .HasColumnType("char(36)");

                b.HasKey("RoleID", "PermissionID")
                    .HasName("PK_RolePermission_RoleId_PermissionId");

                b.HasIndex("PermissionID");

                b.ToTable("role_permission", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Sacrament.Sacrament", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("varchar(16)");

                b.HasKey("ID")
                    .HasName("PK_Sacrament_ID");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Sacrament_Name");

                b.ToTable("sacrament", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.User.User", b =>
            {
                b.Property<Guid>("ID")
                    .HasColumnType("char(36)");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)");

                b.Property<DateOnly>("LastPasswordUpdate")
                    .HasColumnType("date");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)");

                b.HasKey("ID")
                    .HasName("PK_User_Id");

                b.HasIndex("Username")
                    .IsUnique()
                    .HasDatabaseName("UX_User_Username");

                b.ToTable("user", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.User.UserRole", b =>
            {
                b.Property<Guid>("UserID")
                    .HasColumnType("char(36)");

                b.Property<Guid>("RoleID")
                    .HasColumnType("char(36)");

                b.HasKey("UserID", "RoleID")
                    .HasName("PK_UserRole_UserId_RoleId");

                b.HasIndex("RoleID");

                b.ToTable("user_role", (string)null);
            });

        modelBuilder.Entity("MRCD.Domain.Attendance.Attendance", b =>
            {
                b.HasOne("MRCD.Domain.Person.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Attendance_PersonId_Person_ID");

                b.HasOne("MRCD.Domain.User.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Attendance_UserId_User_ID");
            });

        modelBuilder.Entity("MRCD.Domain.Parent.ParentPerson", b =>
            {
                b.HasOne("MRCD.Domain.Parent.Parent", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_ParentPerson_ParentId_Parent_ID");

                b.HasOne("MRCD.Domain.Person.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_ParentPerson_PersonId_Person_ID");
            });

        modelBuilder.Entity("MRCD.Domain.Person.Person", b =>
            {
                b.HasOne("MRCD.Domain.Degree.Degree", null)
                    .WithMany()
                    .HasForeignKey("LastDegreeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Person_DegreeId");
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonCharge", b =>
            {
                b.HasOne("MRCD.Domain.Charge.Charge", null)
                    .WithMany()
                    .HasForeignKey("ChargeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonCharge_ChargeId");

                b.HasOne("MRCD.Domain.Person.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonCharge_PersonId");
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonDocument", b =>
            {
                b.HasOne("MRCD.Domain.Document.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonDocument_DocumentId");

                b.HasOne("MRCD.Domain.Person.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonDocument_PersonId");
            });

        modelBuilder.Entity("MRCD.Domain.Person.PersonSacrament", b =>
            {
                b.HasOne("MRCD.Domain.Person.Person", null)
                    .WithMany()
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonSacrament_PersonId");

                b.HasOne("MRCD.Domain.Sacrament.Sacrament", null)
                    .WithMany()
                    .HasForeignKey("SacramentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PersonSacrament_SacramentId");
            });

        modelBuilder.Entity("MRCD.Domain.Planner.ActivityStage", b =>
            {
                b.HasOne("MRCD.Domain.Planner.Activity", null)
                    .WithMany()
                    .HasForeignKey("ActivityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_ActivityStage_ActivityId_Activity_ID");

                b.HasOne("MRCD.Domain.Planner.Stage", null)
                    .WithMany()
                    .HasForeignKey("StageId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_ActivityStage_StageId_Stage_ID");

                b.HasOne("MRCD.Domain.User.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_ActivityStage_UserId_User_ID");
            });

        modelBuilder.Entity("MRCD.Domain.Role.RolePermission", b =>
            {
                b.HasOne("MRCD.Domain.Role.Permission", null)
                    .WithMany()
                    .HasForeignKey("PermissionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_RolePermission_PermissionId");

                b.HasOne("MRCD.Domain.Role.Role", null)
                    .WithMany()
                    .HasForeignKey("RoleID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_RolePermission_RoleId");
            });

        modelBuilder.Entity("MRCD.Domain.User.UserRole", b =>
            {
                b.HasOne("MRCD.Domain.Role.Role", null)
                    .WithMany()
                    .HasForeignKey("RoleID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_UserRole_RoleId");

                b.HasOne("MRCD.Domain.User.User", null)
                    .WithMany()
                    .HasForeignKey("UserID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_UserRole_UserId");
            });
#pragma warning restore 612, 618
    }
}
